### ISSUE TITLE
inconsistency on % annotation

### ISSUE THREAD

**Issue by livyreal** [UniversalDependencies/UD_French#1]
I found different treatments to `%` in the French Treebank. Sometimes it comes as `SYM`, sometimes it is a `NOUN` with "pourcent" as a lemma.

Is this a mistake? Do you distinguish some uses os `%`?

Examples:

10	les	le	DET	_	Definite=Def|Number=Plur	11	det	_	_
11	plus	plus	ADV	_	_	12	nmod	_	_
12	modestes	modeste	ADJ	_	Gender=Masc|Number=Plur	9	amod	_	_
13	sera	être	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin	14	auxpass	_	_
14	augmenté	augmenter	VERB	_	Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part	0	root	_	_
15	de	de	ADP	_	_	17	case	_	_
16	20	20	NUM	_	_	17	nummod	_	_
17	%	pourcent	NOUN	_	Gender=Masc|Number=Plur	14	nmod	_	_

6	une	un	DET	_	Definite=Ind|Gender=Fem|Number=Sing|PronType=Dem	7	det	_	_
7	diminution	diminution	NOUN	_	Gender=Fem|Number=Sing	5	dobj	_	_
8	de	de	ADP	_	_	10	case	_	_
9	52	52	NUM	_	_	10	nummod	_	_
10	%	%	SYM	_	_	7	nmod	_	_
11	de	de	ADP	_	_	13	case	_	_
12	la	le	DET	_	Definite=Def|Gender=Fem|Number=Sing	13	det	_	_

**Comment by bguil** [comment]
This is a mistake.
This is fixed in the dev version of the corpus (https://github.com/UniversalDependencies/UD_French/commit/21b30eb68aff542acc75da9a0de2747694d0ac47).

**Comment by mcdm** [comment]
Yes this is a mistake. According to the guidelines, it should be SYM. We will fix this. Thanks!

Marie
